insert into CPQ_setup_account_context (account_code, customer_id, currency, language, country_code, is_active)
values ('A000286', 'A000286', 'GBP', 'en-GB', 'GB', true)
on conflict (account_code) do update
set customer_id = excluded.customer_id,
    currency = excluded.currency,
    language = excluded.language,
    country_code = excluded.country_code,
    is_active = excluded.is_active,
    updated_at = now();

insert into CPQ_setup_ruleset (cpq_ruleset, description, bike_type, namespace, header_id, sort_order, is_active)
values ('BBLV6_G-LineMY26', 'Default retained CPQ bike-builder ruleset', 'G Line', 'Default', 'Simulator', 0, true)
on conflict (cpq_ruleset) do update
set description = excluded.description,
    bike_type = excluded.bike_type,
    namespace = excluded.namespace,
    header_id = excluded.header_id,
    sort_order = excluded.sort_order,
    is_active = excluded.is_active,
    updated_at = now();

-- Stock_bike_img_ experimental CSV reference metadata
insert into stock_bike_img_digit_reference (
  stock_bike_img_digit_position,
  stock_bike_img_rule_category_name,
  stock_bike_img_digit_value,
  stock_bike_img_value_meaning
)
values
  (1, 'Handlebar Type', '1', 'Small'),
  (1, 'Handlebar Type', '2', 'Medium'),
  (1, 'Handlebar Type', '3', 'Large'),
  (1, 'Handlebar Type', 'A', 'A Line'),
  (1, 'Handlebar Type', 'H', 'High'),
  (1, 'Handlebar Type', 'M', 'Mid'),
  (1, 'Handlebar Type', 'S', 'Low'),
  (2, 'Speeds', '1', 'One - 1 Speed'),
  (2, 'Speeds', '2', 'Urban - 2 Speeds'),
  (2, 'Speeds', '3', 'Utility - 3 Speeds'),
  (2, 'Speeds', '4', 'Urban - 4 Speeds'),
  (2, 'Speeds', '6', 'Explore - 6 Speeds'),
  (2, 'Speeds', '8', 'TBC - 8 Speeds'),
  (2, 'Speeds', 'L', 'Explore - 12 Speeds'),
  (3, 'Mudguards and Rack', 'E', 'No Mudguards - E-Version'),
  (3, 'Mudguards and Rack', 'L', 'Mudguards - L-Version'),
  (3, 'Mudguards and Rack', 'R', 'Mudguards and Rack - R-Version'),
  (4, 'Territory', '0', 'Code Not in Use'),
  (5, 'Main Frame Colour', '1', 'Lunar Ice'),
  (5, 'Main Frame Colour', '2', 'Cerakote Ti Black'),
  (5, 'Main Frame Colour', '4', 'Forest Green'),
  (5, 'Main Frame Colour', '5', 'Traildust White'),
  (5, 'Main Frame Colour', '6', 'Adventure Orange'),
  (5, 'Main Frame Colour', '9', 'Blasted Ti'),
  (5, 'Main Frame Colour', 'A', 'Bumblebee Yellow'),
  (5, 'Main Frame Colour', 'B', 'Black - Matt'),
  (5, 'Main Frame Colour', 'E', 'Ocean Blue'),
  (5, 'Main Frame Colour', 'F', 'Amethyst Lacquer'),
  (5, 'Main Frame Colour', 'G', 'Racing Green - Matt'),
  (5, 'Main Frame Colour', 'K', 'Black Lacquer - Gloss'),
  (5, 'Main Frame Colour', 'N', 'Dune Sand'),
  (5, 'Main Frame Colour', 'O', 'Bottle Green'),
  (5, 'Main Frame Colour', 'R', 'Turkish Green - Matt'),
  (5, 'Main Frame Colour', 'S', 'Papyrus White - Matt'),
  (5, 'Main Frame Colour', 'T', 'Midnight Black Metallic'),
  (5, 'Main Frame Colour', 'V', 'Bolt Blue Lacquer'),
  (5, 'Main Frame Colour', 'W', 'Yuzu Lime'),
  (5, 'Main Frame Colour', 'X', 'Special Colour X'),
  (5, 'Main Frame Colour', 'Y', 'Special Colour Y'),
  (5, 'Main Frame Colour', 'Z', 'Special Colour Z'),
  (5, 'Main Frame Colour', '3', 'Space Black'),
  (5, 'Main Frame Colour', 'J', 'Flamingo Pink'),
  (5, 'Main Frame Colour', 'M', 'Metallic Green Gloss'),
  (5, 'Main Frame Colour', 'D', 'Cobalt Blue Lacquer'),
  (5, 'Main Frame Colour', 'H', 'Lavender Matt'),
  (5, 'Main Frame Colour', 'L', 'Metallic Blue Gloss'),
  (5, 'Main Frame Colour', 'U', 'Palm Green'),
  (5, 'Main Frame Colour', 'Q', 'Wine Red Matt'),
  (5, 'Main Frame Colour', 'C', 'Veligo Blue'),
  (5, 'Main Frame Colour', '8', 'Purple Violet'),
  (5, 'Main Frame Colour', 'P', 'Pale Brown'),
  (5, 'Main Frame Colour', '7', 'Azure Blue'),
  (6, 'Rear Frame Colour', '1', 'Lunar Ice'),
  (6, 'Rear Frame Colour', '2', 'Cerakote Ti Black'),
  (6, 'Rear Frame Colour', '4', 'Forest Green'),
  (6, 'Rear Frame Colour', '5', 'Traildust White'),
  (6, 'Rear Frame Colour', '6', 'Adventure Orange'),
  (6, 'Rear Frame Colour', '9', 'Blasted Titanium'),
  (6, 'Rear Frame Colour', 'A', 'Bumblebee Yellow'),
  (6, 'Rear Frame Colour', 'B', 'Black - Matt'),
  (6, 'Rear Frame Colour', 'E', 'Ocean Blue'),
  (6, 'Rear Frame Colour', 'F', 'Amethyst Lacquer'),
  (6, 'Rear Frame Colour', 'G', 'Racing Green - Matt'),
  (6, 'Rear Frame Colour', 'K', 'Black Lacquer - Gloss'),
  (6, 'Rear Frame Colour', 'N', 'Dune Sand'),
  (6, 'Rear Frame Colour', 'O', 'Bottle Green'),
  (6, 'Rear Frame Colour', 'R', 'Turkish Green - Matt'),
  (6, 'Rear Frame Colour', 'V', 'Bolt Blue Lacquer'),
  (6, 'Rear Frame Colour', 'W', 'Yuzu Lime'),
  (6, 'Rear Frame Colour', 'X', 'Special Colour X'),
  (6, 'Rear Frame Colour', 'Y', 'Special Colour Y'),
  (6, 'Rear Frame Colour', 'Z', 'Special Colour Z'),
  (6, 'Rear Frame Colour', '3', 'Space Black'),
  (6, 'Rear Frame Colour', 'J', 'Flamingo Pink'),
  (6, 'Rear Frame Colour', 'M', 'Metallic Green Gloss'),
  (6, 'Rear Frame Colour', 'D', 'Cobalt Blue Lacquer'),
  (6, 'Rear Frame Colour', 'H', 'Lavender Matt'),
  (6, 'Rear Frame Colour', 'L', 'Metallic Blue Gloss'),
  (6, 'Rear Frame Colour', 'U', 'Palm Green'),
  (6, 'Rear Frame Colour', 'Q', 'Wine Red Matt'),
  (6, 'Rear Frame Colour', 'S', 'Gloss White'),
  (6, 'Rear Frame Colour', 'C', 'Veligo Blue'),
  (6, 'Rear Frame Colour', '8', 'Purple Violet'),
  (6, 'Rear Frame Colour', 'T', 'Midnight Black Metallic'),
  (6, 'Rear Frame Colour', 'P', 'Pale Brown'),
  (6, 'Rear Frame Colour', '7', 'Azure Blue'),
  (7, 'Front Carrier Block', '0', 'No front carrier block'),
  (7, 'Front Carrier Block', '1', 'Bomber Front End Carrier Block - Category Electric'),
  (7, 'Front Carrier Block', '2', 'forged front carrier block'),
  (7, 'Front Carrier Block', 'A', 'Front Carrier Block - Electric Brixton'),
  (7, 'Front Carrier Block', 'B', 'Front Carrier Block'),
  (7, 'Front Carrier Block', 'E', 'Front Carrier Block - Bromtpon Electric'),
  (7, 'Front Carrier Block', 'G', 'Front Carrier Block - B Electric Greenway'),
  (8, 'Lighting', '0', 'Refls only NO LIGHTS'),
  (8, 'Lighting', '1', 'Rechargeable Battery - Lezyne Hecto Drive 500 XL'),
  (8, 'Lighting', '2', 'Rechargeable Battery - Lezyne Hecto 40'),
  (8, 'Lighting', '3', 'New Brixton E-Bike Light'),
  (8, 'Lighting', 'B', 'BAT lamps Front and Rear'),
  (8, 'Lighting', 'C', 'B+M AVY Integrated Lights on Brompton Electric'),
  (8, 'Lighting', 'D', 'G Volt 60 Battery lamps Front and Rear'),
  (8, 'Lighting', 'E', 'Lezyne E115'),
  (8, 'Lighting', 'S', 'SP Hub Dynamo (SV-8)'),
  (9, 'Saddle Height', '0', 'Standard seat post'),
  (9, 'Saddle Height', '6', 'Extended seat post'),
  (9, 'Saddle Height', 'A', 'Telescopic seat post'),
  (9, 'Saddle Height', 'B', 'Superlight Standard'),
  (9, 'Saddle Height', 'C', 'Superlight Extended'),
  (9, 'Saddle Height', 'T', 'Superlight Telescopic'),
  (10, 'Gear Ratio', '0', 'Standard Gearing'),
  (10, 'Gear Ratio', 'A', '44T Chainring'),
  (10, 'Gear Ratio', 'B', '50T Chainring'),
  (10, 'Gear Ratio', 'C', '54T Chainring'),
  (10, 'Gear Ratio', 'D', '56T Chainring'),
  (10, 'Gear Ratio', 'I', 'Increased Gearing'),
  (10, 'Gear Ratio', 'R', 'Reduced Gearing'),
  (11, 'Saddle', '0', 'Saddle Standard'),
  (11, 'Saddle', '1', 'Custom Saddle'),
  (11, 'Saddle', '2', 'City + Comfy Saddle'),
  (11, 'Saddle', '3', 'Custom AndWander'),
  (11, 'Saddle', '4', 'Brooks B17 Green'),
  (11, 'Saddle', '5', 'Brooks C17 Barbour'),
  (11, 'Saddle', '6', 'Standard Custom'),
  (11, 'Saddle', '7', 'Fizik Aliante R7'),
  (11, 'Saddle', 'A', 'Brooks Cambium C17 All Weather'),
  (11, 'Saddle', 'B', 'Saddle Brooks B17 Special Men'),
  (11, 'Saddle', 'C', 'Saddle Brooks B17 Black Men'),
  (11, 'Saddle', 'D', 'A-Line Saddle'),
  (11, 'Saddle', 'F', 'Custom Saddle - P-TDF'),
  (11, 'Saddle', 'G', 'Custom Saddle - C-TDF'),
  (11, 'Saddle', 'H', 'Saddle Chateaux'),
  (11, 'Saddle', 'L', 'Saddle Brooks B17 Special Female'),
  (11, 'Saddle', 'O', 'Superlight Saddle'),
  (11, 'Saddle', 'Q', 'Saddle Brooks Cambium All Weather TeamGB'),
  (11, 'Saddle', 'T', 'Superlight Carbon Saddle'),
  (11, 'Saddle', 'U', 'Ultra Saddle With Titanium Rails CHPT3'),
  (11, 'Saddle', 'V', 'Custom Saddle - Velo White'),
  (11, 'Saddle', 'W', 'Saddle Standard Wide'),
  (11, 'Saddle', 'X', 'Fizik Terra Argo'),
  (12, 'Tyre', '0', 'Schwalbe Marathon Racer Tyre'),
  (12, 'Tyre', '1', 'Schwalbe ONE Tanwall Tyre'),
  (12, 'Tyre', '2', 'Schwalbe ONE Black Tyre'),
  (12, 'Tyre', '3', 'Conti Tyre Black/Tan 20in'),
  (12, 'Tyre', '4', 'Schwalbe Big Apple Black'),
  (12, 'Tyre', '5', 'Schwalbe Marathon Almotion'),
  (12, 'Tyre', '6', 'Custom AndWander'),
  (12, 'Tyre', 'A', 'A Line Schwalbe Marathon Racer'),
  (12, 'Tyre', 'C', 'Continental Contact Urban 16in'),
  (12, 'Tyre', 'D', 'CONTINENTAL CONTACT URBAN CREAM'),
  (12, 'Tyre', 'G', 'Schwalbe G-One All Round 54-406. Tan wall'),
  (12, 'Tyre', 'J', 'Schwalbe Kojak Tyre'),
  (12, 'Tyre', 'K', 'A Line Schwalbe Kojak Tyre'),
  (12, 'Tyre', 'M', 'Schwalbe Marathon Tyre'),
  (12, 'Tyre', 'R', 'Pirelli Angel RS Black Sidewall'),
  (12, 'Tyre', 'T', 'Marathon Tanwall (Folding) Tyre'),
  (13, 'Brakes', '0', 'Brakes FWD Orientation'),
  (13, 'Brakes', 'R', 'Brakes REV Orientation'),
  (14, 'Pedals', '0', 'Folding pedal LH & RH std'),
  (14, 'Pedals', 'N', 'No Folding pedal LH & RH std'),
  (14, 'Pedals', 'Q', 'Quick Release'),
  (15, 'Saddlebag', '0', 'Code Not in Use'),
  (15, 'Saddlebag', '1', 'Saddle bag Chateaux'),
  (15, 'Saddlebag', '2', 'Leather Saddle Roll Bag'),
  (16, 'Suspension', '0', 'Std Suspension pad WITH clip'),
  (16, 'Suspension', 'F', 'Firm Suspension pad with clip'),
  (16, 'Suspension', 'R', 'Red Xtra Firm Suspension Block - w/ clip'),
  (16, 'Suspension', 'W', 'White Suspension Block'),
  (17, 'Bike Type', '0', 'C Line'),
  (17, 'Bike Type', '1', 'C Line Demo'),
  (17, 'Bike Type', '2', 'P Line BBC'),
  (17, 'Bike Type', '4', 'C Line TeamGB Staff'),
  (17, 'Bike Type', '5', 'C Line Barbour Edition'),
  (17, 'Bike Type', '6', 'C Line Millionth Edition'),
  (17, 'Bike Type', '7', 'NA Artist C Line'),
  (17, 'Bike Type', '8', 'C Line TDF'),
  (17, 'Bike Type', '9', 'C Line Classic Silver'),
  (17, 'Bike Type', 'A', 'A Line'),
  (17, 'Bike Type', 'B', 'C Line Black Edition'),
  (17, 'Bike Type', 'E', 'C Line Electric'),
  (17, 'Bike Type', 'F', 'C Line Electric Demo'),
  (17, 'Bike Type', 'G', 'G Line'),
  (17, 'Bike Type', 'H', 'G Line Electric'),
  (17, 'Bike Type', 'I', 'P Line'),
  (17, 'Bike Type', 'J', 'P Line Electric'),
  (17, 'Bike Type', 'K', 'P Line Demo'),
  (17, 'Bike Type', 'L', 'P Line Shenzhen Junction'),
  (17, 'Bike Type', 'M', 'P Line Electric Demo'),
  (17, 'Bike Type', 'N', 'C Line Nickel'),
  (17, 'Bike Type', 'O', 'C Line Team GB Edition'),
  (17, 'Bike Type', 'R', 'C Line Beyond Edition'),
  (17, 'Bike Type', 'S', 'G Line Electric Demo'),
  (17, 'Bike Type', 'T', 'T Line'),
  (17, 'Bike Type', 'V', 'T Line Demo'),
  (17, 'Bike Type', 'W', 'G Line Demo'),
  (17, 'Bike Type', 'X', 'Special Colour BED'),
  (17, 'Bike Type', 'Y', 'C Line 50th Anniversary'),
  (17, 'Bike Type', '3', 'C Line Electric MK6'),
  (17, 'Bike Type', 'D', 'C Line Electric Brixton'),
  (17, 'Bike Type', 'U', 'T Line Electric'),
  (17, 'Bike Type', 'C', 'C Line MK6'),
  (17, 'Bike Type', 'Q', 'P Line Electric Brixton'),
  (17, 'Bike Type', 'P', 'P Line'),
  (18, 'Toolkit', '0', 'Code Not in Use'),
  (18, 'Toolkit', '1', 'Brompton Toolkit'),
  (19, 'Saddle Light', '0', 'Code Not in Use'),
  (20, 'Model year', '1', 'MY20'),
  (20, 'Model year', '2', 'MY21'),
  (20, 'Model year', '3', 'MY22'),
  (20, 'Model year', '4', 'MY23'),
  (20, 'Model year', '5', 'MY24'),
  (20, 'Model year', '6', 'MY25'),
  (20, 'Model year', '7', 'MY26'),
  (21, 'Options Box (Electric only)', '0', 'None'),
  (21, 'Options Box (Electric only)', '1', 'Option Box 1 - Bag - Charger - UK Plug & Manuals'),
  (21, 'Options Box (Electric only)', '2', 'Option Box 2 - Batt-Bag-Charger-UK Plug & Man'),
  (21, 'Options Box (Electric only)', '3', 'Option Box 3 - Bag - Charger - EU Plug & Manuals'),
  (21, 'Options Box (Electric only)', '4', 'Option Box 4 - Batt,Bag-Charger-EU Plug & Man'),
  (21, 'Options Box (Electric only)', '5', 'Option Box 5 - Bag - Charger - US Plug & Manuals'),
  (21, 'Options Box (Electric only)', '6', 'Option Box 6 - Batt-Bag-Charger-US Plug & Man'),
  (21, 'Options Box (Electric only)', '7', 'Option Box 7 - Manual Only'),
  (21, 'Options Box (Electric only)', '8', 'Option Box 8 - Bag - Charger - AU Plug & Manuals'),
  (21, 'Options Box (Electric only)', '9', 'Option Box 9 - Batt-Bag-Charger-AU Plug & Man'),
  (21, 'Options Box (Electric only)', 'A', 'Option Box A - Bag - Charger - US Plug & Manuals'),
  (21, 'Options Box (Electric only)', 'B', 'Option Box 12 - Batt-Bag-Charger-US Plug & Man'),
  (21, 'Options Box (Electric only)', 'E', 'GE Line Greenway Battery, Small bag, 2A charger UK.'),
  (21, 'Options Box (Electric only)', 'F', 'GE Line Greenway Battery, Small bag, 2A charger EU.'),
  (21, 'Options Box (Electric only)', 'G', 'GE Line Greenway Battery, Small bag, 2A charger US.'),
  (21, 'Options Box (Electric only)', 'H', 'GE Line Greenway Battery, Small bag, 2A charger AU/NZ.'),
  (22, 'Frame Material', 'T', 'All Titanium - Mk6 Extremities'),
  (22, 'Frame Set', '1', 'Standard'),
  (22, 'Frame Set', '2', 'Demo'),
  (22, 'Frame Set', '3', 'Special NA Artist V2'),
  (22, 'Frame Set', '4', 'Special Comfort(City+)'),
  (22, 'Frame Set', '5', 'Special Veligo'),
  (22, 'Frame Set', '6', 'APAC Urban Outdoor'),
  (22, 'Frame Set', '7', 'APAC Premium Silver'),
  (22, 'Frame Set', '8', 'Freelander'),
  (22, 'Frame Set', '9', 'Vitality'),
  (23, 'Component Colour', '1', 'Silver'),
  (23, 'Component Colour', '2', 'Black'),
  (24, 'OnBikeAccessories', '0', 'None'),
  (24, 'OnBikeAccessories', '5', 'Lezyne Pump and Mounts'),
  (24, 'OnBikeAccessories', 'A', 'DTH Kit'),
  (24, 'OnBikeAccessories', 'B', 'DTH Kit FR Reg'),
  (24, 'OnBikeAccessories', 'C', 'DTH Kit & Lezyne Pump and Mounts'),
  (24, 'OnBikeAccessories', 'D', 'DTH Kit FR Reg & Lezyne Pump and Mounts'),
  (24, 'OnBikeAccessories', 'E', 'DTH Kit A-Line & Zefal Brompton Pump'),
  (24, 'OnBikeAccessories', 'F', 'DTH Kit A-Line FR Reg & Zefal Brompton Pump'),
  (24, 'OnBikeAccessories', 'G', 'DTH Kit A-Line'),
  (24, 'OnBikeAccessories', 'H', 'DTH Kit A-Line FR Reg'),
  (24, 'OnBikeAccessories', 'M', 'Flexi Mudguard'),
  (24, 'OnBikeAccessories', 'S', 'Lezyne Pump Silver'),
  (24, 'OnBikeAccessories', 'Z', 'Zefal Brompton Pump'),
  (25, 'Handlebar Stem Colour', '1', 'Lunar Ice'),
  (25, 'Handlebar Stem Colour', '2', 'Cerakote Ti Black'),
  (25, 'Handlebar Stem Colour', '3', 'Pure Orange Matt'),
  (25, 'Handlebar Stem Colour', '4', 'Forest Green'),
  (25, 'Handlebar Stem Colour', '5', 'Baby Pink'),
  (25, 'Handlebar Stem Colour', '6', 'Tempest Blue'),
  (25, 'Handlebar Stem Colour', '8', 'Pall Mall White Gloss'),
  (25, 'Handlebar Stem Colour', '9', 'Blasted Titanium'),
  (25, 'Handlebar Stem Colour', 'A', 'Bumblebee Yellow'),
  (25, 'Handlebar Stem Colour', 'B', 'Black - Matt'),
  (25, 'Handlebar Stem Colour', 'D', 'Oxblood Red Gloss'),
  (25, 'Handlebar Stem Colour', 'E', 'Ocean Blue'),
  (25, 'Handlebar Stem Colour', 'F', 'Amethyst Lacquer'),
  (25, 'Handlebar Stem Colour', 'G', 'Racing Green - Matt'),
  (25, 'Handlebar Stem Colour', 'K', 'Black Lacquer - Gloss'),
  (25, 'Handlebar Stem Colour', 'M', 'Bronze Sky Metallic'),
  (25, 'Handlebar Stem Colour', 'N', 'Dune Sand'),
  (25, 'Handlebar Stem Colour', 'O', 'Bottle Green'),
  (25, 'Handlebar Stem Colour', 'R', 'Turkish Green - Matt'),
  (25, 'Handlebar Stem Colour', 'S', 'Papyrus White - Matt'),
  (25, 'Handlebar Stem Colour', 'T', 'Midnight Black Metallic'),
  (25, 'Handlebar Stem Colour', 'V', 'Bolt Blue Lacquer'),
  (25, 'Handlebar Stem Colour', 'W', 'Yuzu Lime'),
  (25, 'Handlebar Stem Colour', 'X', 'Special Colour X'),
  (25, 'Handlebar Stem Colour', 'Y', 'Special Colour Y'),
  (25, 'Handlebar Stem Colour', 'Z', 'Special Colour Z'),
  (25, 'Handlebar Stem Colour', 'J', 'Flamingo Pink'),
  (25, 'Handlebar Stem Colour', 'H', 'Lavender Matt'),
  (25, 'Handlebar Stem Colour', 'L', 'Metallic Blue Gloss'),
  (25, 'Handlebar Stem Colour', 'U', 'Palm Green'),
  (25, 'Handlebar Stem Colour', 'Q', 'Wine Red Matt'),
  (25, 'Handlebar Stem Colour', 'C', 'Veligo Blue'),
  (25, 'Handlebar Stem Colour', 'P', 'Pale Brown'),
  (25, 'Handlebar Stem Colour', '7', 'Azure Blue'),
  (26, 'Handlebar Pin Colour', '1', 'Lunar Ice'),
  (26, 'Handlebar Pin Colour', '2', 'Yellow Gloss'),
  (26, 'Handlebar Pin Colour', '3', 'Pure Orange Matt'),
  (26, 'Handlebar Pin Colour', '4', 'White - Gloss'),
  (26, 'Handlebar Pin Colour', '5', 'Baby Pink'),
  (26, 'Handlebar Pin Colour', '6', 'Tempest Blue'),
  (26, 'Handlebar Pin Colour', '7', 'Laurel Green Gloss'),
  (26, 'Handlebar Pin Colour', '9', 'Blasted Ti'),
  (26, 'Handlebar Pin Colour', 'A', 'Bumblebee Yellow'),
  (26, 'Handlebar Pin Colour', 'B', 'Black - Matt'),
  (26, 'Handlebar Pin Colour', 'D', 'Oxblood Red Gloss'),
  (26, 'Handlebar Pin Colour', 'E', 'Ocean Blue'),
  (26, 'Handlebar Pin Colour', 'F', 'Amethyst Lacquer'),
  (26, 'Handlebar Pin Colour', 'G', 'Racing Green - Matt'),
  (26, 'Handlebar Pin Colour', 'K', 'Black Lacquer - Gloss'),
  (26, 'Handlebar Pin Colour', 'M', 'Bronze Sky Metallic'),
  (26, 'Handlebar Pin Colour', 'N', 'Dune Sand'),
  (26, 'Handlebar Pin Colour', 'O', 'Bottle Green'),
  (26, 'Handlebar Pin Colour', 'R', 'Turkish Green - Matt'),
  (26, 'Handlebar Pin Colour', 'T', 'Midnight Black Metallic'),
  (26, 'Handlebar Pin Colour', 'V', 'Bolt Blue Lacquer'),
  (26, 'Handlebar Pin Colour', 'W', 'Sulphur Yellow'),
  (26, 'Handlebar Pin Colour', 'X', 'Special Colour X'),
  (26, 'Handlebar Pin Colour', 'Y', 'Special Colour Y'),
  (26, 'Handlebar Pin Colour', 'Z', 'Special Colour Z'),
  (26, 'Handlebar Pin Colour', 'J', 'Flamingo Pink'),
  (26, 'Handlebar Pin Colour', 'S', 'Gloss White'),
  (26, 'Handlebar Pin Colour', 'H', 'Lavender Matt'),
  (26, 'Handlebar Pin Colour', 'L', 'Metallic Blue Gloss'),
  (26, 'Handlebar Pin Colour', 'U', 'Palm Green'),
  (26, 'Handlebar Pin Colour', 'Q', 'Wine Red Matt'),
  (26, 'Handlebar Pin Colour', 'C', 'Veligo Blue'),
  (26, 'Handlebar Pin Colour', 'P', 'Pale Brown'),
  (26, 'Handlebar Pin Colour', '8', 'Purple Violet'),
  (27, 'Front Frame Colour', '1', 'Lunar Ice'),
  (27, 'Front Frame Colour', '4', 'Forest Green'),
  (27, 'Front Frame Colour', '5', 'Traildust White'),
  (27, 'Front Frame Colour', '6', 'Adventure Orange'),
  (27, 'Front Frame Colour', '7', 'Laurel Green Gloss'),
  (27, 'Front Frame Colour', '9', 'Blasted Ti'),
  (27, 'Front Frame Colour', 'B', 'Black - Matt'),
  (27, 'Front Frame Colour', 'C', 'Cerakote Ti Red'),
  (27, 'Front Frame Colour', 'F', 'Amethyst Lacquer'),
  (27, 'Front Frame Colour', 'G', 'Racing Green - Matt'),
  (27, 'Front Frame Colour', 'K', 'Black Lacquer - Gloss'),
  (27, 'Front Frame Colour', 'N', 'Dune Sand'),
  (27, 'Front Frame Colour', 'O', 'Bottle Green'),
  (27, 'Front Frame Colour', 'R', 'Turkish Green - Matt'),
  (27, 'Front Frame Colour', 'S', 'Papyrus White - Matt'),
  (27, 'Front Frame Colour', 'T', 'Midnight Black Metallic'),
  (27, 'Front Frame Colour', 'V', 'Bolt Blue Lacquer'),
  (27, 'Front Frame Colour', 'W', 'Sulphur Yellow'),
  (27, 'Front Frame Colour', 'X', 'Special Colour X'),
  (27, 'Front Frame Colour', 'Y', 'Special Colour Y'),
  (27, 'Front Frame Colour', 'Z', 'Special Colour Z'),
  (27, 'Front Frame Colour', '3', 'Space Black'),
  (27, 'Front Frame Colour', 'J', 'Flamingo Pink'),
  (27, 'Front Frame Colour', 'M', 'Metallic Green Gloss'),
  (27, 'Front Frame Colour', 'D', 'Cobalt Blue Lacquer'),
  (27, 'Front Frame Colour', 'H', 'Lavender Matt'),
  (27, 'Front Frame Colour', 'L', 'Metallic Blue Gloss'),
  (27, 'Front Frame Colour', 'U', 'Palm Green'),
  (27, 'Front Frame Colour', 'Q', 'Wine Red Matt'),
  (27, 'Front Frame Colour', '2', 'Beige Grey'),
  (27, 'Front Frame Colour', 'A', 'Pastel Violet'),
  (27, 'Front Frame Colour', 'P', 'Pale Brown'),
  (27, 'Front Frame Colour', '8', 'Purple Violet'),
  (27, 'Front Frame Colour', 'E', 'Vitality Pink'),
  (28, 'Front Fork Colour', '1', 'Lunar Ice'),
  (28, 'Front Fork Colour', '2', 'Yellow Gloss'),
  (28, 'Front Fork Colour', '4', 'Forest Green'),
  (28, 'Front Fork Colour', '5', 'Traildust White'),
  (28, 'Front Fork Colour', '6', 'Adventure Orange'),
  (28, 'Front Fork Colour', '7', 'Laurel Green Gloss'),
  (28, 'Front Fork Colour', '9', 'Blasted Titanium'),
  (28, 'Front Fork Colour', 'A', 'Bumblebee Yellow'),
  (28, 'Front Fork Colour', 'B', 'Black - Matt'),
  (28, 'Front Fork Colour', 'D', 'Oxblood Red Gloss'),
  (28, 'Front Fork Colour', 'E', 'Ocean Blue'),
  (28, 'Front Fork Colour', 'F', 'Amethyst Lacquer'),
  (28, 'Front Fork Colour', 'G', 'Racing Green - Matt'),
  (28, 'Front Fork Colour', 'K', 'Black Lacquer - Gloss'),
  (28, 'Front Fork Colour', 'M', 'Bronze Sky Metallic'),
  (28, 'Front Fork Colour', 'N', 'Dune Sand'),
  (28, 'Front Fork Colour', 'O', 'Bottle Green'),
  (28, 'Front Fork Colour', 'R', 'Turkish Green - Matt'),
  (28, 'Front Fork Colour', 'S', 'Papyrus White - Matt'),
  (28, 'Front Fork Colour', 'T', 'Midnight Black Metallic'),
  (28, 'Front Fork Colour', 'V', 'Bolt Blue Lacquer'),
  (28, 'Front Fork Colour', 'W', 'Sulphur Yellow'),
  (28, 'Front Fork Colour', 'X', 'Special Colour X'),
  (28, 'Front Fork Colour', 'Y', 'Special Colour Y'),
  (28, 'Front Fork Colour', 'Z', 'Special Colour Z'),
  (28, 'Front Fork Colour', '3', 'Space Black'),
  (28, 'Front Fork Colour', 'J', 'Flamingo Pink'),
  (28, 'Front Fork Colour', 'H', 'Lavender Matt'),
  (28, 'Front Fork Colour', 'L', 'Piccadilly Blue'),
  (28, 'Front Fork Colour', 'U', 'Palm Green'),
  (28, 'Front Fork Colour', 'Q', 'Wine Red Matt'),
  (28, 'Front Fork Colour', 'C', 'Veligo Blue'),
  (28, 'Front Fork Colour', 'P', 'Pale Brown'),
  (28, 'Front Fork Colour', '8', 'Purple Violet'),
  (29, 'Position 29', '1', 'Code 1'),
  (30, 'Grade', '0', 'New'),
  (30, 'Grade', 'A', 'Grade A'),
  (30, 'Grade', 'B', 'Grade B'),
  (30, 'Grade', 'C', 'Grade C')
on conflict (stock_bike_img_digit_position, stock_bike_img_rule_category_name, stock_bike_img_digit_value) do update
set stock_bike_img_value_meaning = excluded.stock_bike_img_value_meaning,
    updated_at = now();
